### ISSUE TITLE
加载速度慢

### ISSUE THREAD

**Issue by Ikaleio** [Xecades/hexo-tag-tiy#1]
看上去`基础URL`使用`Vercel`之类的国外服务部署，加载较慢，影响整个页面加载速度。

可以考虑改成异步加载，或者干脆把`基础URL`部分开源让我们自己部署。

**Comment by Xecades** [comment]
（突然想起了几个月前的 TODO 😂）

项目是开源的：[TIY](https://github.com/Xecades/TIY)，可以自行部署。

但有必要说明一下，这个项目是我很早前写的，在不少方面有些迷惑的操作（~~如果想当年我会nodejs该多好……~~），所以请酌情使用。

另，我现在高三，所以暂时没有精力重构，请谅解。

谢谢。

**Comment by Ikaleio** [comment]
好的~
